### ISSUE TITLE
Refreshing dashboard crashes the app

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#1079]
- SQL Operations Studio Version: 0.28.1

Steps to Reproduce: 

1. Open any dashboard. On the right most side, click on the down (or up) arrow button to hide/reveal the dashboard details. 
2. Click on the `...` to its right and click refresh.

![capture1111](https://user-images.githubusercontent.com/6411451/38385143-f9215188-38c5-11e8-99c8-d6a3eb65aa13.JPG)

Expected - Dashboard refreshes
Actual - The app crashes with the following error - 

```
[uncaught exception]: Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2251 Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:8665:12)
    at Object.debugUpdateDirectives [as updateDirectives] (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12810:15)
    at checkAndUpdateView (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12151:14)
    at callWithDebugContext (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at SafeSubscriber._next (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/dashboard/widgets/properties/propertiesWidget.component.js:57:34)
    at SafeSubscriber.__tryOrUnsub (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\rxjs\Subscriber.js:185:22)
    at Subscriber._next (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\rxjs\Subscriber.js:125:26)
```

**Comment by kburtram** [comment]
@abist I wasn't able to repro.  Please add additional repro steps if available.

**Comment by abist** [comment]
@MattIrv can you add context to this bug if you found something more specific to repro this bug?
