### ISSUE TITLE
Various types of query charts throw exceptions and don't render

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1150]
- SQL Operations Studio Version: 0.28.3

Steps to Reproduce:
Trying to repro https://github.com/Microsoft/sqlopsstudio/issues/32 I hit the below exception

1. Run this query:
`select '2017-06-22T00:00:00' [dt], 791 [count] 
union all select '2017-06-22T01:00:00' [dt], 451
union all select '2017-06-22T02:00:00' [dt], 528
`

2. Click the "View as Chart" button in the bottom Results pane, on the right side.
3. In the Chart Type drop down menu, choose "timeSeries" *(exception happens here)*

```
ERR Cannot read property 'data' of undefined: TypeError: Cannot read property 'data' of undefined
    at BaseChartDirective.updateChartData (D:\xplat\sqlopsstudio\node_modules\ng2-charts\charts\charts.js:88:43)
    at BaseChartDirective.ngOnChanges (D:\xplat\sqlopsstudio\node_modules\ng2-charts\charts\charts.js:39:26)
    at checkAndUpdateDirectiveInline (D:\xplat\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:10819:19)
    at checkAndUpdateNodeInline (D:\xplat\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12245:17)
    at checkAndUpdateNode (D:\xplat\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12184:16)
    at debugCheckAndUpdateNode (D:\xplat\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12887:59)
    at debugCheckDirectivesFn (D:\xplat\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12828:13)
    at Object.eval [as updateDirectives] (ng:///QueryOutputModule/TimeSeriesChart.ngfactory.js:61:5)
    at Object.debugUpdateDirectives [as updateDirectives] (D:\xplat\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12813:21)
    at checkAndUpdateView (D:\xplat\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12151:14)
```

**Comment by anthonydresser** [comment]
What commit was this on? I did some fixing around this area earlier this week
