### ISSUE TITLE
Cannot re-add a removed dashboard tab without reopening dashboard first

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#1499]
- SQL Operations Studio Version: master 8fce79f

Steps to Reproduce:
1. Open a dashboard that has some extension-contributed tabs (like sp_whoisactive)
2. Close the tab
3. Click the + button and try to re-add the tab

Expected behavior: The tab reopens
Actual behavior: Dashboard goes blank and the following error gets shown in the console:

```
ERROR Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:8665:12)
    at Object.debugUpdateDirectives [as updateDirectives] (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:12810:15)
    at checkAndUpdateView (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:12151:14)
    at callWithDebugContext (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:12753:12)
    at ViewRef_.detectChanges (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:10225:63)
    at TabComponent.set [as active] (file:///Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/tab.component.js:35:26)
    at file:///Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/panel.component.js:122:49
    at ZoneDelegate.invoke (/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:388:26)
    at Object.onInvoke (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:4156:37)
console.(anonymous function) @ /Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:2251
View_ServerDashboardPage_0 @ ng:///ModuleClass/ServerDashboardPage.ngfactory.js:497
proxyClass @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/compiler/bundles/compiler.umd.js:14101
DebugContext_.logError @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:13153
ErrorHandler.handleError @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:1151
(anonymous) @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:10753
schedulerFn @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:3870
SafeSubscriber.__tryOrUnsub @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:238
SafeSubscriber.next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:185
Subscriber._next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:125
Subscriber.next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:89
Subject.next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subject.js:55
EventEmitter.emit @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:3844
TabHeaderComponent.closeTab @ Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/tabHeader.component.js:60
CloseTabAction.run @ Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/tabActions.js:25
ActionRunner.runAction @ Users/mairvine/code/sqlopsstudio/out/vs/base/common/actions.js:184
ActionRunner.run @ Users/mairvine/code/sqlopsstudio/out/vs/base/common/actions.js:177
BaseActionItem.onClick @ Users/mairvine/code/sqlopsstudio/out/vs/base/browser/ui/actionbar/actionbar.js:129
(anonymous) @ Users/mairvine/code/sqlopsstudio/out/vs/base/browser/ui/actionbar/actionbar.js:111
runCallback @ timers.js:672
tryOnImmediate @ timers.js:645
processImmediate @ timers.js:617
/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:2251 ERROR CONTEXT DebugContext_
console.(anonymous function) @ /Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:2251
View_ServerDashboardPage_0 @ ng:///ModuleClass/ServerDashboardPage.ngfactory.js:497
proxyClass @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/compiler/bundles/compiler.umd.js:14101
DebugContext_.logError @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:13153
ErrorHandler.handleError @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:1156
(anonymous) @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:10753
schedulerFn @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:3870
SafeSubscriber.__tryOrUnsub @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:238
SafeSubscriber.next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:185
Subscriber._next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:125
Subscriber.next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subscriber.js:89
Subject.next @ /Users/mairvine/code/sqlopsstudio/node_modules/rxjs/Subject.js:55
EventEmitter.emit @ /Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:3844
TabHeaderComponent.closeTab @ Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/tabHeader.component.js:60
CloseTabAction.run @ Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/tabActions.js:25
ActionRunner.runAction @ Users/mairvine/code/sqlopsstudio/out/vs/base/common/actions.js:184
ActionRunner.run @ Users/mairvine/code/sqlopsstudio/out/vs/base/common/actions.js:177
BaseActionItem.onClick @ Users/mairvine/code/sqlopsstudio/out/vs/base/browser/ui/actionbar/actionbar.js:129
(anonymous) @ Users/mairvine/code/sqlopsstudio/out/vs/base/browser/ui/actionbar/actionbar.js:111
runCallback @ timers.js:672
tryOnImmediate @ timers.js:645
processImmediate @ timers.js:617
/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:2251 [uncaught exception]: Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
console.(anonymous function) @ /Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:2251
onError @ index.js:39
(anonymous) @ index.js:121
ZoneDelegate.invokeTask @ /Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:421
Zone.runTask @ /Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:188
ZoneTask.invokeTask @ /Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:496
ZoneTask.invoke @ /Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:485
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ /Users/mairvine/code/sqlopsstudio/.build/electron/SQL Operations Studio.app/Contents/Resources/electron.asar/renderer/init.js:135
/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:2251 Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:8665:12)
    at Object.debugUpdateDirectives [as updateDirectives] (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:12810:15)
    at checkAndUpdateView (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:12151:14)
    at callWithDebugContext (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:12753:12)
    at ViewRef_.detectChanges (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:10225:63)
    at TabComponent.set [as active] (file:///Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/tab.component.js:35:26)
    at file:///Users/mairvine/code/sqlopsstudio/out/sql/base/browser/ui/panel/panel.component.js:122:49
    at ZoneDelegate.invoke (/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:388:26)
    at Object.onInvoke (/Users/mairvine/code/sqlopsstudio/node_modules/@angular/core/bundles/core.umd.js:4156:37)
```

**Comment by anthonydresser** [comment]
I couldn't directly repro this but I found a auxiliary error in this same situation. #1557
