### ISSUE TITLE
Dashboard: Silently errors out when opened

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#1522]
**SQL Operations Studio Version**: `0.30.3`

**Steps to Reproduce**:

1. Open the databases folder in OE for any server.
2. Open 2-3 different databases in succession. 

**Expected** - The dashboard for that database opens (perhaps in a new tab)
**Actual** - SQL Ops errors out silently throwing this error -

```
C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2251 ERROR Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:8665:12)
    at Object.debugUpdateDirectives [as updateDirectives] (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12810:15)
    at checkAndUpdateView (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12151:14)
    at callWithDebugContext (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at TabComponent.set [as active] (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/panel/tab.component.js:35:26)
    at file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/panel/panel.component.js:122:49
    at ZoneDelegate.invoke (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
```
And the dashboard is empty. Here's a screenshot - 

![new-errors](https://user-images.githubusercontent.com/6411451/40752504-ac8a6e24-6424-11e8-909a-f5892f4454a5.JPG)

It's possible that it's related to this error which I have a fix for - https://github.com/Microsoft/sqlopsstudio/pull/1519

Could also be related to this - https://github.com/Microsoft/sqlopsstudio/issues/1499

**Comment by anthonydresser** [comment]
I can't repro this. All I get is the empty dashboard which is covered by #1549

**Comment by kburtram** [comment]
@anthonydresser sounds good.  I close this as "no repro".  I think #1549 has a consistent repro and appears similar to this.

**Comment by abist** [comment]
I had a fix checked in for a similar issue. Looks like it fixed this as well.
