### ISSUE TITLE
Agent.AgentAlertTests.TestHandleCreateAgentAlertsRequest is flaky

### ISSUE THREAD

**Issue by madelinemacd** [Microsoft/sqlopsstudio#1553]
See https://ci.appveyor.com/project/kburtram/sqltoolsservice/build/1.0.2157

Stack Trace:
```
Failed   Microsoft.SqlTools.ServiceLayer.IntegrationTests.Agent.AgentAlertTests.TestHandleCreateAgentAlertsRequest
Error Message:
 System.ApplicationException : AgentAlertSR.CannotCreateNewAlert
---- Microsoft.SqlServer.Management.Smo.FailedOperationException : Create failed for Alert 'Test Job Name'. 
-------- Microsoft.SqlServer.Management.Common.ExecutionFailureException : An exception occurred while executing a Transact-SQL statement or batch.
------------ System.Data.SqlClient.SqlException : Supply either a non-zero message ID, non-zero severity, non-null performance condition, or non-null WMI namespace and query.
   at Microsoft.SqlTools.ServiceLayer.Agent.AgentAlert.CreateOrUpdate() in C:\projects\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\Agent\Jobs\AgentAlert.cs:line 132
   at Microsoft.SqlTools.ServiceLayer.Agent.AgentService.CreateOrUpdateAgentAlert(ConnectionInfo connInfo, AgentAlertInfo alert) in C:\projects\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\Agent\AgentService.cs:line 358
   at Microsoft.SqlTools.ServiceLayer.Agent.AgentService.<>c__DisplayClass21_0.<<HandleCreateAgentAlertRequest>b__0>d.MoveNext() in C:\projects\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\Agent\AgentService.cs:line 323
```

**Comment by abist** [comment]
Hey @madelinemacd, you should open this issue on this repo instead - https://github.com/Microsoft/sqltoolsservice
