### ISSUE TITLE
Scripting.ScriptingServiceTests.VerifyScriptAsExecuteStoredProcedure is flaky

### ISSUE THREAD

**Issue by madelinemacd** [Microsoft/sqlopsstudio#1554]
See https://ci.appveyor.com/project/kburtram/sqltoolsservice/build/1.0.2157

```
{"jsonrpc":"2.0","method":"textDocument/intelliSenseReady","params":{"ownerUri":"C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp359E.tmp"}}Failed   Microsoft.SqlTools.ServiceLayer.IntegrationTests.Scripting.ScriptingServiceTests.VerifyScriptAsExecuteStoredProcedure
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at Microsoft.SqlTools.ServiceLayer.IntegrationTests.Scripting.ScriptingServiceTests.VerifyScriptingResult(ScriptingResult result, List`1 expectedScripts) in C:\projects\sqltoolsservice\test\Microsoft.SqlTools.ServiceLayer.IntegrationTests\Scripting\ScriptingServiceTests.cs:line 363
   at lambda_method(Closure , ScriptingResult )
   at Moq.It.<>c__DisplayClass2_0`1.<Is>b__0(TValue value)
   at Moq.Match`1.Matches(Object value)
   at Moq.Matchers.Matcher.Matches(Object value)
   at Moq.MethodCall.Matches(ICallContext call)
   at Moq.Mock.<>c__DisplayClass56_0.<VerifyCalls>b__0(ICallContext ac)
   at System.Linq.Enumerable.WhereListIterator`1.GetCount(Boolean onlyIfCheap)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
   at Moq.Mock.Verify[T,TResult](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
   at Moq.Mock`1.Verify[TResult](Expression`1 expression)
   at Microsoft.SqlTools.ServiceLayer.IntegrationTests.Scripting.ScriptingServiceTests.VerifyScriptAsForMultipleObjects(String query, List`1 scriptingObjects, ScriptingOperationType operation, List`1 expectedScripts) in C:\projects\sqltoolsservice\test\Microsoft.SqlTools.ServiceLayer.IntegrationTests\Scripting\ScriptingServiceTests.cs:line 337
   at Microsoft.SqlTools.ServiceLayer.IntegrationTests.Scripting.ScriptingServiceTests.VerifyScriptAsForMultipleObjects(String query, List`1 scriptingObjects, ScriptingOperationType operation, List`1 expectedScripts) in C:\projects\sqltoolsservice\test\Microsoft.SqlTools.ServiceLayer.IntegrationTests\Scripting\ScriptingServiceTests.cs:line 351
   at Microsoft.SqlTools.ServiceLayer.IntegrationTests.Scripting.ScriptingServiceTests.VerifyScriptAs(String query, ScriptingObject scriptingObject, ScriptingOperationType operation, String expectedScript) in C:\projects\sqltoolsservice\test\Microsoft.SqlTools.ServiceLayer.IntegrationTests\Scripting\ScriptingServiceTests.cs:line 292
   at Microsoft.SqlTools.ServiceLayer.IntegrationTests.Scripting.ScriptingServiceTests.VerifyScriptAsExecuteStoredProcedure() in C:\projects\sqltoolsservice\test\Microsoft.SqlTools.ServiceLayer.IntegrationTests\Scripting\ScriptingServiceTests.cs:line 191
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
```

**Comment by madelinemacd** [comment]
Accidentally put on the wrong repo, closing and moving to https://github.com/Microsoft/sqltoolsservice
