### ISSUE TITLE
Extension debugging: modelbuilder.flexLayout() occasionally fails due to angular module issues

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#1631]
This is intermittent, but @MattIrv also sees it and it's worth investigating. Occasionally when debugging the extensions against the Ops Studio dev build, it fails with an issue where Angular component loader couldn't find it. This is very strange, and for me occasionally happens on restart of Ops Studio.

It may be worth investigating in case it affects real users.

**Comment by llali** [comment]
ERR No component factory found for LoadingComponent. Did you add it to @NgModule.entryComponents?: Error: No component factory found for LoadingComponent. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3330:34)
    at _NullComponentFactoryResolver.resolveComponentFactory (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3348:15)
    at CodegenComponentFactoryResolver.resolveComponentFactory (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3390:87)
    at ModelComponentWrapper.loadComponent (file:///D:/git/sqlopsstudio/out/sql/parts/modelComponents/modelComponentWrapper.component.js:97:67)
    at ModelComponentWrapper.ngAfterViewInit (file:///D:/git/sqlopsstudio/out/sql/parts/modelComponents/modelComponentWrapper.component.js:60:22)
    at callProviderLifecycles (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11168:18)
    at callElementProvidersLifecycles (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11143:13)
    at callLifecycleHooksChildrenFirst (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11127:17)
    at checkAndUpdateView (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12159:5)
    at callViewAction (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callWithDebugContext (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at ModelViewContent.ViewBase.initializeModel (file:///D:/git/sqlopsstudio/out/sql/parts/modelComponents/viewBase.js:39:28)
    at file:///D:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:51:27
    at MainThreadModelView.execModelViewAction (file:///D:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:89:26)
    at MainThreadModelView.$initializeModel (file:///D:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:50:25)
    at RPCProtocol._doInvokeHandler (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:215:27)
    at RPCProtocol._invokeHandler (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:200:54)
    at RPCProtocol._receiveRequest (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:155:50)
    at RPCProtocol._receiveOneMessage (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:138:26)
    at file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:75:92
    at file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:248:21
    at Emitter.fire (file:///D:/git/sqlopsstudio/out/vs/base/common/event.js:103:38)
    at Socket.<anonymous> (file:///D:/git/sqlopsstudio/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
    at ZoneDelegate.invokeTask (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2251   ERR No component factory found for FormContainer. Did you add it to @NgModule.entryComponents?: Error: No component factory found for FormContainer. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3330:34)
    at _NullComponentFactoryResolver.resolveComponentFactory (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3348:15)
    at CodegenComponentFactoryResolver.resolveComponentFactory (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3390:87)
    at ModelComponentWrapper.loadComponent (file:///D:/git/sqlopsstudio/out/sql/parts/modelComponents/modelComponentWrapper.component.js:97:67)
    at ModelComponentWrapper.ngAfterViewInit (file:///D:/git/sqlopsstudio/out/sql/parts/modelComponents/modelComponentWrapper.component.js:60:22)
    at callProviderLifecycles (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11168:18)
    at callElementProvidersLifecycles (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11143:13)
    at callLifecycleHooksChildrenFirst (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11127:17)
    at checkAndUpdateView (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12159:5)
    at callViewAction (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callWithDebugContext (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (D:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at ModelViewContent.ViewBase.initializeModel (file:///D:/git/sqlopsstudio/out/sql/parts/modelComponents/viewBase.js:39:28)
    at file:///D:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:51:27
    at MainThreadModelView.execModelViewAction (file:///D:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:89:26)
    at MainThreadModelView.$initializeModel (file:///D:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:50:25)
    at RPCProtocol._doInvokeHandler (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:215:27)
    at RPCProtocol._invokeHandler (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:200:54)
    at RPCProtocol._receiveRequest (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:155:50)
    at RPCProtocol._receiveOneMessage (file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:138:26)
    at file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:75:92
    at file:///D:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:248:21
    at Emitter.fire (file:///D:/git/sqlopsstudio/out/vs/base/common/event.js:103:38)
    at Socket.<anonymous> (file:///D:/git/sqlopsstudio/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
    at ZoneDelegate.invokeTask (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (D:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
