### ISSUE TITLE
Unable to connect to any datasource

### ISSUE THREAD

**Issue by dotariel** [Microsoft/sqlopsstudio#1718]
Issue Type: <b>Bug</b>

Platform: Darwin
OS: Mac OS 10.13.5 (High Sierra)

SQL Ops will not connect to any SQL Server (local, Azure). A wireshark trace on tcp.port==1433 does not show any traffic.

NOTE: I am able to connect to Azure/local SQL docker container using Visual Studio Code + MSSQL extension.

Steps to Reproduce:

1. Install SQL Operations Studio
2. Open SQL Operations Studio
3. Add new connection:  (host=localhost, port=1433, u=sa, p=<password>)
4. SQL Operations Studio hangs indefinitely

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:34:32.192Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (5.75GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@dotariel do you see any exceptions being raised in the `Help->Toggle Developer Tools` Console?  

We are using the same connection backend as the VS Code MSSQL extension, so if that works then you should be able to get SQL Ops working.  You may try deleting the app and redownloading to make sure everything was installed correctly.

**Comment by dotariel** [comment]
The console does not show any output, exception or otherwise. The network
tab shows no activity, either. Also, I have attempted to download/install
the application 3 times.

**Comment by dotariel** [comment]
Update: I reinstalled SQL Operations Studio, and noticed this exception on startup:

```
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension 'Microsoft.mssql' failed: Cannot find module './resourceProvider/resourceProvider'.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension `Microsoft.mssql` failed:  Cannot find module './resourceProvider/resourceProvider'
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 Activating extension 'Microsoft.mssql' failed: Cannot find module './resourceProvider/resourceProvider'.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 Extension 'Microsoft.profiler' failed to activate. Reason: dependency 'Microsoft.mssql' failed to activate.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Here is the error stack:  Error: Cannot find module './resourceProvider/resourceProvider'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.load [as _load] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46196:33)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:23:28)
	at Object.<anonymous> (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:165:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.load [as _load] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46196:33)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.nodeRequire [as __$__nodeRequire] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/loader.js:1663:32)
	at loadCommonJSModule (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46613:25)
	at ExtHostExtensionService._doActivateExtension (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46525:17)
	at ExtHostExtensionService._activateExtension (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46497:25)
	at Object.actualActivateExtension (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46385:38)
	at ExtensionsActivator._activateExtension (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28926:78)
	at /Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28912:89
	at Array.map (native)
	at ExtensionsActivator._activateExtensions (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28912:57)
	at ExtensionsActivator._activateExtensions (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28914:25)
	at /Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28915:30
	at Object.notifySuccess [as _notify] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6245:59)
	at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5927:30)
	at Promise_ctor._run (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6143:29)
	at Promise_ctor._completed (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6111:18)
	at argDone (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6888:37)
	at Promise.then.errors.(anonymous function) (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6913:78)
	at Object.notifySuccess [as _notify] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6245:59)
	at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5927:30)
	at _Base.Class.derive._creator._run (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6143:29)
	at _Base.Class.derive._creator._completed (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6111:18)
	at CompletePromise_ctor.CompletePromise_then [as then] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6641:49)
	at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5822:28)
	at _Base.Class.derive._creator._run (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6143:29)
	at _Base.Class.derive._creator._setCompleteValue (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6127:18)
	at Object.notifySuccess [as _notify] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6245:28)
	at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5927:30)
	at Promise_ctor._run (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6143:29)
	at Promise_ctor._completed (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6111:18)
	at argDone (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6888:37)
	at Promise.then.errors.(anonymous function) (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6913:78)
	at Object.notifySuccess [as _notify] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6245:59)
	at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5927:30)
	at Promise_ctor._run (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6143:29)
	at Promise_ctor._completed (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6111:18)
	at argDone (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6888:37)
	at Promise.then.errors.(anonymous function) (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6913:78)
	at Object.notifySuccess [as _notify] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6245:59)
	at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5927:30)
	at Promise_ctor._run (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6143:29)
	at Promise_ctor._completed (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6111:18)
	at LazyPromise.resolveOk (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:33913:22)
	at RPCProtocol._receiveReply (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:40678:26)
	at RPCProtocol._receiveOneMessage (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:40642:26)
	at /Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:40573:92
	at /Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:40746:21
	at /Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8185:70
	at Emitter.fire (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7947:38)
	at Socket.<anonymous> (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12405:46)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Extension 'Microsoft.profiler' failed to activate. Reason: dependency 'Microsoft.mssql' failed to activate.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
```

I tried reinstalling the MSSQL extension from VS Code, but the startup error persists.

**Comment by kburtram** [comment]
@dotariel the `MSSQL for VS Code` isn't expected to work when installed in SQL Ops Studio, so I'd recommend uninstalling that extension in SQL Ops.

The issue with `resourceProvider` looks similar to the issue we're tracking in https://github.com/Microsoft/sqlopsstudio/issues/728.  I do see one issue with how we import the `resourceProvider` module that I'd expect to cause problems on Linux.  Not sure if the fix would help you, but I'll make a test build with a proposed fix to see if it helps.  I'll give you an update later today.

**Comment by dotariel** [comment]
@kburtram After reading through #728, I noticed someone else experiencing a similar issue mention that they are using a case-sensitive filesystem. I am also using a case-sensitive filesystem.

**Comment by kburtram** [comment]
@dotariel I noticed that the casing of the module `require` was mismatched and published this PR to resolve that issue https://github.com/Microsoft/sqlopsstudio/pull/1731.

This test build contains the change from #1731 https://sqlopsbuilds.blob.core.windows.net/stage/sqlops-macos-0.31.1-resourceprovider.zip.  If possible, could you please test out this build?

We typically hit case-sensitivity issues on Linux, but in this case some part of the build publishing system is "recasing" file names in such a way that the mismatch only occurs on macOS.  Unfortunately my macOS machine isn't case sensitive so I don't have a local repro.

**Comment by dotariel** [comment]
@kburtram This build works for me. I am able to connect to my SQL Server container.
