### ISSUE TITLE
Save as JSON/EXCEL/CSV not work

### ISSUE THREAD

**Issue by MicheleLevada** [Microsoft/sqlopsstudio#1728]
- SQL Operations Studio Version:
Versione 0.30.6
Commit df7e3ec7d52a82febee5b597a1019cabf021b883
Data 2018-06-19T21:45:43.589Z
Shell 1.7.12
Renderer 58.0.3029.110
Nodo 7.9.0
Architettura x64

Steps to Reproduce:
1. Execution basic query
2. When i try to export data.. nothing happens
![exportdata](https://user-images.githubusercontent.com/31312056/41920936-04b182de-7962-11e8-8f90-44727cc0d2c1.png)

**Comment by kburtram** [comment]
@MicheleLevada are you seeing any error message in the `Help->Toggle Developer Tools` Console?  I haven't  been able to repro this locally yet.

**Comment by MicheleLevada** [comment]
yep...


`C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2251 ERROR TypeError: Cannot read property 'uri' of undefined
    at Object.getRootPath (workbench.main.js:134601)
    at ResultSerializer.get [as rootPath] (workbench.main.js:219660)
    at ResultSerializer.promptForFilepath (workbench.main.js:219669)
    at ResultSerializer.saveResults (workbench.main.js:219589)
    at DataService.sendSaveRequest (workbench.main.js:219998)
    at QueryComponent.GridParentComponent.handleContextClick (workbench.main.js:87018)
    at Object.functionality (workbench.main.js:98520)
    at Object.eval [as handleEvent] (QueryComponent.ngfactory.js:148)
    at Object.handleEvent (C:\Program Files\SQL Operations Studio\resources\app\node_modules.asar\@angular\core\bundles\core.u…:11921)
    at Object.handleEvent (C:\Program Files\SQL Operations Studio\resources\app\node_modules.asar\@angular\core\bundles\core.u…:12624)
    at dispatchEvent (C:\Program Files\SQL Operations Studio\resources\app\node_modules.asar\@angular\core\bundles\core.u…:8821)
    at bindLen (C:\Program Files\SQL Operations Studio\resources\app\node_modules.asar\@angular\core\bundles\core.u…:9413)
    at HTMLAnchorElement.DomRendererFactory2.DomRendererFactory2.sharedStylesHost.eventManager (C:\Program Files\SQL Operations Studio\resources\app\node_modules.asar\@angular\platform-browser\bu…:2696)`

**Comment by kburtram** [comment]
@MicheleLevada I published a PR that will avoid the exception that you provided above https://github.com/Microsoft/sqlopsstudio/pull/2179.

It looks like there is something about the Workspace file you have loaded where the first folder doesn't have a URI for some reason.  Do you know if there is anything noteworthy about the folders added to your active Workspace file?

**Comment by rkonnad** [comment]
I apologize if this is the right place for this being that the issue has been closed, but I'm still having the same issue on SQL Ops for macOS.

I'm running SQL Operations Studio version 0.32.8.

Here is the console output:
`/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251   ERR Cannot read property 'fromRow' of undefined: TypeError: Cannot read property 'fromRow' of undefined
    at file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:230306:66
    at Object.notifySuccess [as _notify] (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14713:59)
    at Object.enter (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14395:30)
    at _Base.Class.derive._creator._run (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14611:29)
    at _Base.Class.derive._creator._completed (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14579:18)
    at ZoneDelegate.invoke (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:388:26)
    at Zone.run (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:138:43)
    at /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:858:57
    at ZoneDelegate.invokeTask (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:188:47)
    at drainMicroTaskQueue (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:595:35)
    at ZoneTask.invokeTask (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:500:21)
    at EventEmitter.ZoneTask.ZoneTask.cancelFn.invoke (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:485:48)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 WARNING: Promise with no error callback:78
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 Object {exception: TypeError: Cannot read property 'fromRow' of undefined
    at file:///Applications/SQL Operations St…, error: null, promise: _…e.C…s.d…e._creator, handler: undefined, id: 78…}
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 TypeError: Cannot read property 'fromRow' of undefined
    at workbench.main.js:230306
    at Object.notifySuccess [as _notify] (workbench.main.js:14713)
    at Object.enter (workbench.main.js:14395)
    at _Base.Class.derive._creator._run (workbench.main.js:14611)
    at _Base.Class.derive._creator._completed (workbench.main.js:14579)
    at ZoneDelegate.invoke (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:388)
    at Zone.run (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:138)
    at /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:858
    at ZoneDelegate.invokeTask (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:421)
    at Zone.runTask (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:188)
    at drainMicroTaskQueue (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:595)
    at ZoneTask.invokeTask (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:500)
    at EventEmitter.ZoneTask.ZoneTask.cancelFn.invoke (/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:485)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:194)`

**Comment by kburtram** [comment]
@abist could you please verify this is working as expected in `master`.  And confirm which fix we took after `0.32.8` that resolved the issue that @rkonnad is hitting?

**Comment by abist** [comment]
@kburtram This is working fine in master and the new insider release (0.33.2).
@rkonnad Please try out our latest insider release here - https://github.com/Microsoft/sqlopsstudio/releases. This bug should be fixed in the new release.
