### ISSUE TITLE
Connection Error: The server was not found or was not accessible.

### ISSUE THREAD

**Issue by MrCroft** [Microsoft/sqlopsstudio#191]
- SQL Operations Studio Version: 0.23.6
- OS: Windows 10 PRO (1709)

Just found out about SQL Operations Studio and wanted to use it in development, instead of Heidi.

I've created a new connection, inputting the following details:
Server name: 192.168.56.101 (this being the IP of my VM - running a CentOS image with MySQL among other services)
Authentication type: SQL Login
Username: root
Password: *my-password*
Database name: [blank] (I've also tried putting an existing database name in this input, makes no difference)

When clicking on "Connect", after a 15-20 seconds delay (during which the loading indicator is shown), it prompts me with the "Connection Error" popup.
Here is the complete error message in a gist: https://gist.github.com/MrCroft/e33a967d96b27211f0c494862d91e1db

The exact same settings are used in other sql clients to connect and work just fine. I've even tried adding the port to the IP (so `192.168.56.101:3306` instead of just the IP), with no luck.

![image](https://user-images.githubusercontent.com/2809154/33130740-fdf6a2d6-cf9c-11e7-92af-f9554fbe30ac.png)

**Comment by macvag** [comment]
The same here on Ubuntu 16.04
```
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (Connection refused 127.0.0.1:1433) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 127.0.0.1:1433
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.<ConnectAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Connection refused 127.0.0.1:1433
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.<ConnectAsync>d__22.MoveNext()<---

   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass22_0.<TryGetConnection>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<TryOpenConnection>d__46.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 542
ClientConnectionId:00000000-0000-0000-0000-000000000000
```

```
 mssql-server.service - Microsoft SQL Server Database Engine
   Loaded: loaded (/lib/systemd/system/mssql-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Πεμ 2017-11-23 16:14:11 EET; 1s ago
     Docs: https://docs.microsoft.com/en-us/sql/linux
  Process: 14554 ExecStart=/opt/mssql/bin/sqlservr (code=exited, status=1/FAILURE)
 Main PID: 14554 (code=exited, status=1/FAILURE)
Nov 23 16:14:11 shadow systemd[1]: mssql-server.service: Unit entered failed state.
Nov 23 16:14:11 shadow systemd[1]: mssql-server.service: Failed with result 'exit-code'.
Nov 23 16:14:11 shadow systemd[1]: mssql-server.service: Service hold-off time over, scheduling restart.
Nov 23 16:14:11 shadow systemd[1]: Stopped Microsoft SQL Server Database Engine.
Nov 23 16:14:11 shadow systemd[1]: mssql-server.service: Start request repeated too quickly.
Nov 23 16:14:11 shadow systemd[1]: Failed to start Microsoft SQL Server Database Engine.
```

**Comment by Sprunth** [comment]
Had the same issue; turns out I didn't enter the server name/db name correctly.

**Comment by MrCroft** [comment]
@Sprunth I wish that was the case, even if I'd have made a fool of myself 😄 
But it's not, I've double checked and triple checked and kept trying.
Using the same credentials, I can connect with other SQL clients like Heidi.

Also, in the docs it says that "Database name" is optional. But just to make sure, I've also tried inputting an existing database name - same error.
Unfortunately I have no idea how can I debug anything to try and help further.

**Comment by kburtram** [comment]
@MrCroft currently SQL Ops Studio only supports SQL Server instances.  Based on the port used in the connection above I'm guessing you're trying to connect to a MySQL instance?  If so, that would result in the error mentioned above.

**Comment by MrCroft** [comment]
@kburtram You're right. I'm not a backend developer, I simply assumed that SQL/MySQL are roughly the same.
Well... In this case, I'm hoping to see MySQL support soon (have no ideea how easy or how difficult would that be).
Till then, I guess this issue can be closed since it wasn't opened with a feature request in mind.

**Comment by krishnareddyML** [comment]
I have the same issue in Ubuntu 16.04, and I am trying to connect SQL server 2008 R2

System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=45; handshake=200; [Login] initialization=5; authentication=10; [Post-Login] complete=14040;  ---> System.ComponentModel.Win32Exception (0x80004005): Unknown error 258
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass22_0.<TryGetConnection>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<TryOpenConnection>d__46.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 542
ClientConnectionId:219ccba4-bef3-4d73-9e8c-1b57c892eece
Error Number:-2,State:0,Class:11

**Comment by krishnareddyML** [comment]
And I got following message in terminal while running sqlops
**sudo ./sqlops 
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell**

**Comment by kevcunnane** [comment]
Krishna - for SQL Server 2008 R2 you must update to 2008 R2 SP3 to connect. .Net Core requires this as there’s a security vulnerability in earlier versions and the drivers intentionally do not connect to these versions.

**Comment by kburtram** [comment]
@MrCroft we're tracking adding support for other relation DBs in this issue https://github.com/Microsoft/sqlopsstudio/issues/56.

@krishnareddyML please open an issue related to SQL Server 2008 if @kevcunnane suggestion doesn't address you're concern.

**Comment by dtelaroli** [comment]
@MrCroft @macvag You can use the DBeaver, now, it's the best multiplatform cross database manager. It works fine with SQLServer 2008 and other databases that you can't imagine.
I like VSCode so I tried SQLOpS, but, I'm disappointed, maybe after some years it will be good.
