### ISSUE TITLE
Import extension broke packaged builds

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#2187]
- SQL Operations Studio Version: master 

Steps to Reproduce:
Run `gulp vscode-win32-x64` from the command line

The command fails with the following error:
```
[11:22:58] Starting 'vscode-win32-x64'...
Creating vsix for /Users/mairvine/code/sqlopsstudio/extensions/agent result:/Users/mairvine/code/agent.vsix
Creating vsix for /Users/mairvine/code/sqlopsstudio/extensions/import result:/Users/mairvine/code/import.vsix
Creating vsix for /Users/mairvine/code/sqlopsstudio/extensions/profiler result:/Users/mairvine/code/profiler.vsix
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Command failed: npm list --production --parseable --depth=99999
npm ERR! invalid: dataprotocol-client@0.2.4 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/dataprotocol-client
npm ERR! extraneous: vscode-languageclient@3.5.0 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/vscode-languageclient
npm ERR! invalid: service-downloader@0.1.4 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/service-downloader
npm ERR! extraneous: decompress@4.2.0 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/decompress
npm ERR! extraneous: eventemitter2@5.0.1 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/eventemitter2
npm ERR! extraneous: http-proxy-agent@2.1.0 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/http-proxy-agent
npm ERR! extraneous: https-proxy-agent@2.2.1 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/https-proxy-agent
npm ERR! extraneous: tmp@0.0.33 /Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/tmp

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm list --production --parseable --depth=99999' } } reason: { Error: Command failed: npm list --production --parseable --depth=99999
```

**Comment by aaomidi** [comment]
https://github.com/Microsoft/sqlops-dataprotocolclient/pull/21 Once this gets approved, a version bump should fix our issues.

**Comment by aaomidi** [comment]
https://github.com/Microsoft/sqlopsstudio/blob/master/extensions/import/package.json#L101 This is already being done on this side too.
