### ISSUE TITLE
Import service fails to start on mac

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#2188]
- SQL Operations Studio Version: master

Steps to Reproduce:
1. Start SQL Ops Studio

The following error will be shown in the debug console:
```

[Microsoft.import]spawn EACCES
zone-node.js:2251
Error: spawn EACCES
zone-node.js:2251
	at exports._errnoException (util.js:1050:11)
	at ChildProcess.spawn (internal/child_process.js:319:11)
	at Object.exports.spawn (child_process.js:390:9)
	at SqlOpsDataClient.createMessageTransports (/Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/vscode-languageclient/lib/main.js:328:36)
	at SqlOpsDataClient.createConnection (/Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/vscode-languageclient/lib/client.js:1854:21)
	at SqlOpsDataClient.resolveConnection (/Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/vscode-languageclient/lib/client.js:1697:44)
	at SqlOpsDataClient.start (/Users/mairvine/code/sqlopsstudio/extensions/import/node_modules/vscode-languageclient/lib/client.js:1628:14)
	at __dirname.startService.serverdownloader.getOrDownloadServer.then.e (/Users/mairvine/code/sqlopsstudio/extensions/import/out/services/serviceClient.js:55:41)
	at <anonymous>
```

This is the same error we've seen before when the service binaries don't get built on Mac. We should figure out how to set the executable permissions correctly when building these binaries on all platforms.

**Comment by aaomidi** [comment]
This should be solved.

**Comment by aaomidi** [comment]
Seems like the build agent's archive task doesn't preserve the extra attributes like file permissions.

Solution suggestions:
- Use tar.gz on OSX.
- Get the downloader to set the executable bit after downloading the files.

**Comment by aaomidi** [comment]
Closing issue, if problem isn't solved please reopen.
