### ISSUE TITLE
Doesn't start on windows if path contains # character

### ISSUE THREAD

**Issue by Tragen** [Microsoft/sqlopsstudio#237]
I unpacked everything to
B:\# sql\sqlops-windows-0.23.6
when I start it, I see two processes in task manager but nothing happens. When I kill the processes and move the folder directly to b:\ everything is running fine.

**Comment by MattIrv** [comment]
Looks like this bug is present in VS Code as well and is coming from our dependency on VS Code.

It happens because several VS Code files attempt to refer to other source files using `URI.parse` on the installation file path, which does not work as expected when the installation path contains a `#` character since it parses it as a URI fragment identifier rather than part of the path.

Stack traces (observed by running from the command line):
```
The factory method of "vs/base/node/paths" has thrown an exception
{ Error: Cannot find module 'c:\'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\#\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.nodeRequire [as __$__nodeRequire] (c:\#\resources\app\out\vs\loader.js:1649:28)
    at Object.<anonymous> (c:\#\resources\app\out\vs\code\electron-main\main.js:10952:25)
    at Function.Module._safeInvokeFunction (c:\#\resources\app\out\vs\loader.js:907:45)
    at Function.Module._invokeFactory (c:\#\resources\app\out\vs\loader.js:926:29)
    at Module.complete (c:\#\resources\app\out\vs\loader.js:939:36) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'c:\'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\#\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.nodeRequire [as __$__nodeRequire] (c:\#\resources\app\out\vs\loader.js:1649:28)
    at Object.<anonymous> (c:\#\resources\app\out\vs\code\electron-main\main.js:10952:25)
    at Function.Module._safeInvokeFunction (c:\#\resources\app\out\vs\loader.js:907:45)
    at Function.Module._invokeFactory (c:\#\resources\app\out\vs\loader.js:926:29)
    at Module.complete (c:\#\resources\app\out\vs\loader.js:939:36)
The factory method of "vs/platform/node/package" has thrown an exception
{ Error: Cannot find module 'c:\package.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\#\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.nodeRequire [as __$__nodeRequire] (c:\#\resources\app\out\vs\loader.js:1649:28)
    at Object.<anonymous> (c:\#\resources\app\out\vs\code\electron-main\main.js:13521:31)
    at Function.Module._safeInvokeFunction (c:\#\resources\app\out\vs\loader.js:907:45)
    at Function.Module._invokeFactory (c:\#\resources\app\out\vs\loader.js:926:29)
    at Module.complete (c:\#\resources\app\out\vs\loader.js:939:36) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'c:\package.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\#\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.nodeRequire [as __$__nodeRequire] (c:\#\resources\app\out\vs\loader.js:1649:28)
    at Object.<anonymous> (c:\#\resources\app\out\vs\code\electron-main\main.js:13521:31)
    at Function.Module._safeInvokeFunction (c:\#\resources\app\out\vs\loader.js:907:45)
    at Function.Module._invokeFactory (c:\#\resources\app\out\vs\loader.js:926:29)
    at Module.complete (c:\#\resources\app\out\vs\loader.js:939:36)
The factory method of "vs/platform/node/product" has thrown an exception
{ Error: Cannot find module 'c:\product.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\#\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.nodeRequire [as __$__nodeRequire] (c:\#\resources\app\out\vs\loader.js:1649:28)
    at Object.<anonymous> (c:\#\resources\app\out\vs\code\electron-main\main.js:13533:27)
    at Function.Module._safeInvokeFunction (c:\#\resources\app\out\vs\loader.js:907:45)
    at Function.Module._invokeFactory (c:\#\resources\app\out\vs\loader.js:926:29)
    at Module.complete (c:\#\resources\app\out\vs\loader.js:939:36) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'c:\product.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\#\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.nodeRequire [as __$__nodeRequire] (c:\#\resources\app\out\vs\loader.js:1649:28)
    at Object.<anonymous> (c:\#\resources\app\out\vs\code\electron-main\main.js:13533:27)
    at Function.Module._safeInvokeFunction (c:\#\resources\app\out\vs\loader.js:907:45)
    at Function.Module._invokeFactory (c:\#\resources\app\out\vs\loader.js:926:29)
    at Module.complete (c:\#\resources\app\out\vs\loader.js:939:36)
The factory method of "vs/code/electron-main/main" has thrown an exception
TypeError: paths.getDefaultUserDataPath is not a function
    at parseUserDataDir (c:\#\resources\app\out\vs\code\electron-main\main.js:13867:83)
    at EnvironmentService.get (c:\#\resources\app\out\vs\code\electron-main\main.js:13628:39)
    at EnvironmentService.descriptor.(anonymous function) [as userDataPath] (c:\#\resources\app\out\vs\code\electron-main\main.js:168:31)
    at new EnvironmentService (c:\#\resources\app\out\vs\code\electron-main\main.js:13584:47)
    at create (c:\#\resources\app\out\vs\code\electron-main\main.js:2205:14)
    at InstantiationService._createInstance (c:\#\resources\app\out\vs\code\electron-main\main.js:13306:43)
    at InstantiationService._createAndCacheServiceInstance (c:\#\resources\app\out\vs\code\electron-main\main.js:13365:41)
    at InstantiationService._getOrCreateServiceInstance (c:\#\resources\app\out\vs\code\electron-main\main.js:13313:29)
    at Object.get (c:\#\resources\app\out\vs\code\electron-main\main.js:13241:44)
    at c:\#\resources\app\out\vs\code\electron-main\main.js:23014:47
TypeError: paths.getDefaultUserDataPath is not a function
    at parseUserDataDir (c:\#\resources\app\out\vs\code\electron-main\main.js:13867:83)
    at EnvironmentService.get (c:\#\resources\app\out\vs\code\electron-main\main.js:13628:39)
    at EnvironmentService.descriptor.(anonymous function) [as userDataPath] (c:\#\resources\app\out\vs\code\electron-main\main.js:168:31)
    at new EnvironmentService (c:\#\resources\app\out\vs\code\electron-main\main.js:13584:47)
    at create (c:\#\resources\app\out\vs\code\electron-main\main.js:2205:14)
    at InstantiationService._createInstance (c:\#\resources\app\out\vs\code\electron-main\main.js:13306:43)
    at InstantiationService._createAndCacheServiceInstance (c:\#\resources\app\out\vs\code\electron-main\main.js:13365:41)
    at InstantiationService._getOrCreateServiceInstance (c:\#\resources\app\out\vs\code\electron-main\main.js:13313:29)
    at Object.get (c:\#\resources\app\out\vs\code\electron-main\main.js:13241:44)
    at c:\#\resources\app\out\vs\code\electron-main\main.js:23014:47
```

**Comment by MattIrv** [comment]
@kburtram this repros for me on Windows by installing to a directory with a '#' character in it as described. Do we want to take this for August? It is an upstream issue from VS Code

**Comment by alanrenmsft** [comment]
@kburtram @MattIrv  Do we have an issue tracking this in VS repo?

**Comment by alanrenmsft** [comment]
I searched in VSCode git repo and couldn't find an issue tracking this, so I created one myself: https://github.com/Microsoft/vscode/issues/56506

I'll keep an eye on it...

**Comment by alanrenmsft** [comment]
upstream issue: https://github.com/electron/electron/issues/10311
