### ISSUE TITLE
Edit Data grid doesn't properly escape all characters

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2421]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Run Edit Data on a table with problematic content.  For example, `AdventureWorks.Person.Person`

Expected: Results render correctly

Actual: Some HTML content is written on top of grid content

![image](https://user-images.githubusercontent.com/599935/45120482-17683380-b113-11e8-82a4-0900a8a4a948.png)

**Comment by kburtram** [comment]
Here is the exception I see in the Dev Console.

```
D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 [uncaught exception]: Error: Selection model is not set
console.(anonymous function) @ D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280
D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 Error: Selection model is not set
    at SlickGrid.setSelectedRows (D:\xplat\sqlopsstudio\node_modules\slickgrid\slick.grid.js:3835:15)
    at RowNumberColumn.handleHeaderClick (file:///D:/xplat/sqlopsstudio/out/sql/base/browser/ui/table/plugins/rowNumberColumn.plugin.js:33:27)
    at SlickGrid.<anonymous> (file:///D:/xplat/sqlopsstudio/out/sql/base/browser/ui/table/plugins/rowNumberColumn.plugin.js:19:87)
    at Event.notify (D:\xplat\sqlopsstudio\node_modules\slickgrid\slick.core.js:145:35)
    at trigger (D:\xplat\sqlopsstudio\node_modules\slickgrid\slick.grid.js:1235:18)
    at HTMLDivElement.handleHeaderClick (D:\xplat\sqlopsstudio\node_modules\slickgrid\slick.grid.js:2818:9)
    at HTMLDivElement.dispatch (D:\xplat\sqlopsstudio\node_modules\jquery\dist\jquery.js:5110:27)
    at HTMLDivElement.$event.dispatch (file:///D:/xplat/sqlopsstudio/node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js:382:30)
    at HTMLDivElement.elemData.handle (D:\xplat\sqlopsstudio\node_modules\jquery\dist\jquery.js:4918:28)
```

**Comment by anthonydresser** [comment]
this should be fixed
