### ISSUE TITLE
Connection Timeout Expired

### ISSUE THREAD

**Issue by panjiswt** [Microsoft/sqlopsstudio#374]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-05T22:46:14.815Z)
- OS Version: Linux x64 4.8.0-54-generic
---

Steps to Reproduce:

1.System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=180; handshake=458; [Login] initialization=4; authentication=24; [Post-Login] complete=14050;  ---> System.ComponentModel.Win32Exception (0x80004005): Unknown error 258
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass22_0.<TryGetConnection>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<TryOpenConnection>d__46.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 542
ClientConnectionId:627c132a-ebdc-4d86-bd9e-3d0108dc05b2
Error Number:-2,State:0,Class:11

2. How do I fix this?

**Comment by kburtram** [comment]
@panjiswt this looks like a generic exception from SqlClient library when a connection to a SQL Server fails.  Connections can fail for numerous reasons, such as incorrect server name\IP, incorrect port or firewall configuration, server is offline, dropped network connection, etc.  If you provide additional details about the scenario I may have more specific guidance.

Have you tried connecting to the SQL Server from the target machine using a different tool, like sqlcmd?  This may help narrow down the possible cause of the connection failure.

**Comment by panjiswt** [comment]
![screenshot from 2017-12-29 10-21-14](https://user-images.githubusercontent.com/34529676/34428791-d18529ae-ec82-11e7-9c44-af6a5fcae59f.png)

**Comment by saurabh500** [comment]
@panjiswt This is a timeout expiration during the last phase of Login to the SQL server. 
As @kburtram mentioned, try another client like SqlCmd, 
Also try increasing the timeout for connection from Sql Ops Studio to something > 15 seconds. 

To further troubleshoot this from your end, you could look into the error logs of the Sql Server to see if there is any information about why the connection was taking long.

**Comment by kburtram** [comment]
Closing out older issues that don't have a pending request.  Please reactive if there's still anything we should look at for this issue.
