### ISSUE TITLE
Can't connect to a server via SQL login when user name contains domain

### ISSUE THREAD

**Issue by tmikoss** [Microsoft/sqlopsstudio#399]
- SQL Operations Studio Version: 0.24.1, OS X

Steps to Reproduce:
* Create a new connection with SQL Login auth type;
* Fill in user name in "domain\user" format, along with server name and password;
* Click connect;
* Error message "Login failed for user 'domain\user'." appears.

The server is SQL Server 2012 SP3. I am able to connect to it from the same machine via different application (SQLPro Studio). Also, I am able to successfully connect to a different server via SQL Ops Studio, where username does not have the "domain\" component.

"Copy details" on the error message yields following:
```
System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'domain\user'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass22_0.<TryGetConnection>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<TryOpenConnection>d__46.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 542
ClientConnectionId:dc75eb4b-7d76-48af-9ccb-df6507102a48
Error Number:18456,State:1,Class:14
```

**Comment by R-i-c-h-B** [comment]
Hi Tmikoss... I'm not sure I fully understood this, but are you expecting to be connecting using an Active Directory username or have you created an actual SQL login with there a domain\user format?  
I ask as I have never managed to create a SQL Login of that format, it doesn't much care for the \ character in usernames.

However I often see people (and myself) trying to use a 'SQL Login' type connection for an AD account, and that never works as far as I can tell.

**Comment by tmikoss** [comment]
It seems that the other app I was comparing to (SQLPro Studio) was silently changing the connection type to windows auth (from sql login I initially set), and I guess that's the reason why it worked. But as the database was set up by a customer, I can't comment with absolute certainty.

Either way, this seems to be a bug between the chair and the keyboard, rather than in the software :)

But while we're on the topic - is there a way to use windows auth without joining the device to domain as outlined [here](https://docs.microsoft.com/en-us/sql/sql-operations-studio/enable-kerberos)? When I switch the connection type to windows auth, the username / password fields are grayed out. As I'm working with multiple customers, I'd rather not fully join my device to one of their domains just for database access.

**Comment by R-i-c-h-B** [comment]
Not sure if this will get through to the right place but here goes :)

On windows you can have at it in 2 ways, one of which is more likely to
work I think.  Run the application using runas /netonly.  So locally it is
your current windows login but over the network it runs as the suplied
credential.

For more specific network credentials the credential manager tool in
windows will also work... but it seems to need each individual server name
and port.

From linux I have not worked it out yet... any volunteers?

Cheers

Rich

**Comment by genio** [comment]
There is no way to do that from a non-domain machine on Linux/OS X.  You have to create a SQL Login user with enough privileges to do what you need to do from those OSes.

That being said, it would be really nice to be able to pass AD credentials for Windows Login users without joining a machine to the domain.

1. I don't have domain permissions to join a machine to the domain
1. I'm not joining my personal machine to the domain
1. I'm trying to work over VPN from a linux machine and if I'm going to RDP into a machine on the domain to do the work, I might as well login to the one that already has SSMS installled and this software fails to have a point (other than looking nicer).

**Comment by tmikoss** [comment]
Is that a "no way to do that in context of current code" or "no way to do that, period"?
