### ISSUE TITLE
Connection dialog advanced button doesn't work

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#553]
- SQL Operations Studio Version: 0.26.0

Clicking on "Advanced..." button in the connection dialog gives the following error - 

```
C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2251 Cannot set property 'onfocus' of undefined: TypeError: Cannot set property 'onfocus' of undefined
    at Object.createOptionElement (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/modal/optionsDialogHelper.js:55:30)
    at OptionsDialog.fillInOptions (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/modal/optionsDialog.js:130:37)
    at Builder.<anonymous> (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/modal/optionsDialog.js:202:27)
    at Builder.doElement (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:358:20)
    at Builder.element (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:337:25)
    at OptionsDialog.open (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/modal/optionsDialog.js:201:51)
    at AdvancedPropertiesController.showDialog (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/connection/connectionDialog/advancedPropertiesController.js:29:33)
    at ConnectionController.handleOnAdvancedProperties (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionController.js:54:38)
    at Object.onAdvancedProperties (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionController.js:29:66)
    at file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionWidget.js:144:46
```

**Comment by abist** [comment]
@anthonydresser Can you verify if this is related to the slickgrid issue?

**Comment by anthonydresser** [comment]
Based on the call stack, and the fact that the connection dialog doesn't use anything related to slickgrid its highly unlikely that it is related.

**Comment by MattIrv** [comment]
If it helps it looks like this starts failing in the 1/19/18 daily build, after working in the previous successful 1/17/18 build.
