### ISSUE TITLE
Restore Task is broken

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#599]
Click on the Restore task from the dashboard. Resulting error -

```
C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2251 Unhandled Promise rejection: Cannot read property 'className' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'className' of undefined
    at measureScrollbar (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:510:65)
    at init (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:336:52)
    at new SlickGrid (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:4281:5)
    at new Table (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/table/table.js:37:26)
    at Builder.<anonymous> (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/disasterRecovery/restore/restoreDialog.js:169:47)
    at Builder.doElement (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:276:20)
    at Builder.div (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:178:25)
    at Builder.<anonymous> (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/disasterRecovery/restore/restoreDialog.js:167:38)
    at Builder.doElement (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:276:20)
    at Builder.div (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:178:25) TypeError: Cannot read property 'className' of undefined
    at measureScrollbar (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:510:65)
    at init (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:336:52)
    at new SlickGrid (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:4281:5)
    at new Table (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/base/browser/ui/table/table.js:37:26)
    at Builder.<anonymous> (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/disasterRecovery/restore/restoreDialog.js:169:47)
    at Builder.doElement (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:276:20)
    at Builder.div (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:178:25)
    at Builder.<anonymous> (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/disasterRecovery/restore/restoreDialog.js:167:38)
    at Builder.doElement (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:276:20)
    at Builder.div (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/vs/base/browser/builder.js:178:25)
```

**Comment by abist** [comment]
@anthonydresser I know you had a fix out in this PR -
 https://github.com/Microsoft/sqlopsstudio/pull/552/files

However, it doesn't seem to work. I noticed that even after a clean and fresh npm install, it gets the older commit version from `package.json` using ` "slickgrid": "github:anthonydresser/SlickGrid#2.3.12"`. My `yarn.lock` file also mentions this -
```
"slickgrid@github:anthonydresser/SlickGrid#2.3.12":
  version "2.3.12"
  resolved "https://codeload.github.com/anthonydresser/SlickGrid/tar.gz/5610e05166cd7068dcf196498ae20054382b1684"
```
Do you think we should update the `package.json` file instead?
