### ISSUE TITLE
Restore task does nothing from dashboard

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#668]
1. Click on Restore task on the dashboard (Task grid). Nothing happens, and no error is thrown.

2. Right click on any database on the object-explorer and click on "Restore". Nothing happens, but the following error is thrown - 

```
C:\Users\adbist\Downloads\sqlops-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2251 Unhandled Promise rejection: Cannot read property 'className' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'className' of undefined
    at measureScrollbar (C:\Users\adbist\Downloads\sqlops-windows\resources\app\node_modules\slickgrid\slick.grid.js:510)
    at init (C:\Users\adbist\Downloads\sqlops-windows\resources\app\node_modules\slickgrid\slick.grid.js:336)
    at new SlickGrid (C:\Users\adbist\Downloads\sqlops-windows\resources\app\node_modules\slickgrid\slick.grid.js:4281)
    at new Table (workbench.main.js:35017)
    at Builder.<anonymous> (workbench.main.js:171044)
    at Builder.doElement (workbench.main.js:28540)
    at Builder.div (workbench.main.js:28442)
    at Builder.<anonymous> (workbench.main.js:171042)
    at Builder.doElement (workbench.main.js:28540)
    at Builder.div (workbench.main.js:28442) TypeError: Cannot read property 'className' of undefined
    at measureScrollbar (C:\Users\adbist\Downloads\sqlops-windows\resources\app\node_modules\slickgrid\slick.grid.js:510:65)
    at init (C:\Users\adbist\Downloads\sqlops-windows\resources\app\node_modules\slickgrid\slick.grid.js:336:52)
    at new SlickGrid (C:\Users\adbist\Downloads\sqlops-windows\resources\app\node_modules\slickgrid\slick.grid.js:4281:5)
    at new Table (file:///C:/Users/adbist/Downloads/sqlops-windows/resources/app/out/vs/workbench/workbench.main.js:35017:26)
    at Builder.<anonymous> (file:///C:/Users/adbist/Downloads/sqlops-windows/resources/app/out/vs/workbench/workbench.main.js:171044:47)
    at Builder.doElement (file:///C:/Users/adbist/Downloads/sqlops-windows/resources/app/out/vs/workbench/workbench.main.js:28540:20)
    at Builder.div (file:///C:/Users/adbist/Downloads/sqlops-windows/resources/app/out/vs/workbench/workbench.main.js:28442:25)
    at Builder.<anonymous> (file:///C:/Users/adbist/Downloads/sqlops-windows/resources/app/out/vs/workbench/workbench.main.js:171042:38)
    at Builder.doElement (file:///C:/Users/adbist/Downloads/sqlops-windows/resources/app/out/vs/workbench/workbench.main.js:28540:20)
    at Builder.div (file:///C:/Users/adbist/Downloads/sqlops-windows/resources/app/out/vs/workbench/workbench.main.js:28442:25)
```

**Comment by kburtram** [comment]
@anthonydresser this seems similar to the previous Restore dialog issue I saw with the angular-slickgrid vbump.  Please see https://github.com/Microsoft/sqlopsstudio/issues/599 for reference.  Reverting the slickgrid vbump resolved the issue in that case.
