### ISSUE TITLE
New connection button doesn't work

### ISSUE THREAD

**Issue by maurodx** [Microsoft/sqlopsstudio#873]
- SQL Operations Studio Version: 0.26.7

Steps to Reproduce:
Clicking on "New Connection" the panel for new connection setup doesn't appear.

On developer console i got:
Activating extension `Microsoft.mssql` failed:
extensions_modules_1.SqlToolsServiceClient.getInstance is not a function

Here is the error stack:  TypeError: extensions_modules_1.SqlToolsServiceClient.getInstance is not a function
	at new MainController (d:\Tools\sqlops-windows\resources\app\extensions\mssql\client\out\controllers\mainController.js:27:67)
	at activate (d:\Tools\sqlops-windows\resources\app\extensions\mssql\client\out\main.js:9:26)
	at Function.ExtHostExtensionService._callActivateOptional (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:32727:67)
	at Function.ExtHostExtensionService._callActivate (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:32718:25)
	at d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:32680:48
	at Object.notifySuccess [as _notify] (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5996:59)
	at Object.enter (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5678:30)
	at Promise_ctor._run (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5894:29)
	at Promise_ctor._completed (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5862:18)
	at argDone (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:6639:37)
	at _Base.Class.derive.join.keys.forEach.Promise.then.errors.(anonymous function) (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:6664:78)
	at Object.notifySuccess [as _notify] (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5996:59)
	at Object.enter (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5678:30)
	at Promise_ctor._run (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5894:29)
	at Promise_ctor._completed (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5862:18)
	at argDone (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:6639:37)
	at _Base.Class.derive.join.keys.forEach.Promise.then.errors.(anonymous function) (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:6664:78)
	at Object.notifySuccess [as _notify] (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5996:59)
	at Object.enter (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5678:30)
	at Promise_ctor._run (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5894:29)
	at Promise_ctor._completed (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:5862:18)
	at LazyPromise.resolveOk (d:\Tools\sqlops-windows\resources\app\out\vs\workbench\node\extensionHostProcess.js:24009:22)

**Comment by coltonhurst** [comment]
I also cannot create add a new connection. I just downloaded it- glad I found this, because I couldn't figure out why it wasn't working for me.

Question- where can I go to see any error output from the sqlops?
When I press the "Add Connection" button, nothing happens in the sqlops dev tools (toggled by Help->"Toggle Developer Tools").

I also don't observe any output in the system.log from the Console app.

Note:
I'm running OS X 10.13.3

**Comment by kburtram** [comment]
@maurodx the issue you're getting seems like there are missing files in the application directory.  Could you please try deleting the application directory and re-extracting the ZIP file to make sure all the files are decompressed successfully?

@coltonhurst I suspect that perhaps the MicrosoftSqlToolsServiceLayer application isn't being started for some reason (if possible, could you please check if that app is running when SQL Ops is running using something like ` ps -ef | egrep SqlTools`)  Usually on macOS this would be related to a missing dependencies or some security issue.  For security issues sometimes moving the application from Downloads to the Application folder can help with some of the GateKeeper settings.  If you have any additional repro steps or error details it may help to narrow down what's happening.

**Comment by maurodx** [comment]
@kburtram now it's working! The problem was that I have unzipped the archive inside the old directory and probably something from the 0.23 release interfere with the current one.
Next time i'll remove the old one before extracting the new one

**Comment by coltonhurst** [comment]
@kburtram I ran `ps -ef | egrep SqlTools` after starting sql ops and this is the output I get:

`501   982   953   0 10:31AM ttys000    0:00.00 egrep SqlTools`

So it looks like that's the only process that's running. I don't see something called MicrosoftSqlToolsServiceLayer running.

As far as reproducible steps, all I did was download the zip from the link in gitlab, unzip the application, and I've tried running it straight from the downloads folder as well as moving it to the Applications folder and running it there. So far nothing works. Thanks for the help! Please let me know what else I can try.

**Comment by michael-hay** [comment]
I had the same issue.  Selecting the "New Connection" button did not do anything.  Be sure you have all the dependencies installed as listed here (scroll down):

https://docs.microsoft.com/en-us/sql/sql-operations-studio/download

I was missing libunwind8 on ubuntu17.  After installing all the required dependencies it's now working for me.

**Comment by coltonhurst** [comment]
@michael-hay good idea. I looked however, and did not see any dependencies for OS X. I'm running High Sierra 10.13.3. Are there dependencies I'm not seeing that need to be installed?

**Comment by kburtram** [comment]
I'll close this issue since the original problem discussed seems resolved.  For the macOS problem there are a couple active issues specifically for that.  We don't have an internal repro for that, so it's hard to make progress there.
